<?php

namespace App\Models\nomina\GAPE;

use Illuminate\Database\Eloquent\Model;

class NominaGapeEmpleado extends Model
{
    //
    protected $primaryKey = 'id';
    protected $table = 'nomina_gape_empleado';

    protected $casts = [
        'calculado' => 'boolean',
        'afectado' => 'boolean',
        'calculadoextraordinario' => 'boolean',
        'afectadoextraordinario' => 'boolean',
        'interfazcheqpaqw' => 'boolean',
        'modificacionneto' => 'boolean',
        'calculoptu' => 'boolean',
        'calculoaguinaldo' => 'boolean',
        'cambiocotizacionimss' => 'boolean',
        'Subcontratacion' => 'boolean',
        'carga_masiva' => 'boolean',
        // agrega más según lo necesites
    ];

    protected $fillable = [
        'id_nomina_gape_empresa',
        'idempleado',
        'estado_empleado',
        'iddepartamento',
        'idpuesto',
        'idtipoperiodo',
        'idturno',
        'codigoempleado',
        'nombre',
        'apellidopaterno',
        'apellidomaterno',
        'nombrelargo',
        'fechanacimiento',
        'lugarnacimiento',
        'estadocivil',
        'sexo',
        'curpi',
        'curpf',
        'numerosegurosocial',
        'umf',
        'rfc',
        'homoclave',
        'cuentapagoelectronico',
        'sucursalpagoelectronico',
        'bancopagoelectronico',
        'estadoempleado',
        'sueldodiario',
        'fechasueldodiario',
        'sueldovariable',
        'fechasueldovariable',
        'sueldopromedio',
        'fechasueldopromedio',
        'sueldointegrado',
        'fechasueldointegrado',
        'calculado',
        'afectado',
        'calculadoextraordinario',
        'afectadoextraordinario',
        'interfazcheqpaqw',
        'modificacionneto',
        'fechaalta',
        'cuentacw',
        'tipocontrato',
        'basecotizacionimss',
        'tipoempleado',
        'basepago',
        'formapago',
        'zonasalario',
        'calculoptu',
        'calculoaguinaldo',
        'modificacionsalarioimss',
        'altaimss',
        'bajaimss',
        'cambiocotizacionimss',
        'expediente',
        'telefono',
        'codigopostal',
        'direccion',
        'poblacion',
        'estado_emp',
        'nombrepadre',
        'nombremadre',
        'numeroafore',
        'fechabaja',
        'causabaja',
        'sueldobaseliquidacion',
        'campoextra1',
        'campoextra2',
        'campoextra3',
        'fechareingreso',
        'ajustealneto',
        'timestamp',
        'cidregistropatronal',
        'ccampoextranumerico1',
        'ccampoextranumerico2',
        'ccampoextranumerico3',
        'ccampoextranumerico4',
        'ccampoextranumerico5',
        'cestadoempleadoperiodo',
        'cfechasueldomixto',
        'csueldomixto',
        'NumeroFonacot',
        'CorreoElectronico',
        'TipoRegimen',
        'ClabeInterbancaria',
        'EntidadFederativa',
        'Subcontratacion',
        'ExtranjeroSinCURP',
        'TipoPrestacion',
        'DiasVacTomadasAntesdeAlta',
        'DiasPrimaVacTomadasAntesdeAlta',
        'TipoSemanaReducida',
        'Teletrabajador',
        'Equipo',
        'Insumo',
        'DireccionTeletrabajo',
        'carga_masiva',
        'estado',
        'curpCompleto',
    ];
}
